language: ruby

rvm:
  - ruby-2.4.1

notifications:
  email: false

before_script:
  - rake install

jobs:
  include:
    - stage: "Markdown Validation"
      addons:
        apt:
          packages:
            - pandoc
            - libxml2-utils
            - devscripts
            - build-essential
            - lintian
            - debhelper
      before_script:
        - sudo add-apt-repository -y ppa:mike42/mdcheckr
        - sudo apt-get update
        - sudo apt-get -y install mdcheckr
      script:
        - mdcheckr README.md
    - stage: "Links & Duplicate Testing"
      before_script:
        - gem install awesome_bot
      script:
        - awesome_bot README.md --white-list gph.is,giphy,travis-ci.org,codeload,badge,rubydoc,rubygems,circleci,codeship,blob/master